pipeline {
    agent any

    stages {
        stage("git"){ //git에 브랜치 url, credentialsId는 젠킨스에 등록한 인증으로 
            steps{
                git branch: 'develop', credentialsId: 'gitlab', url: 'https://lab.ssafy.com/s08-webmobile1-sub2/S08P12A405.git'
            }
        }
        stage('build') {
            steps{
                sh "ls -a"
                dir('backend') { //gradle 권한 설정 후 gradle로 도커 이미지 빌드하는 명령어 실행 
                    dir('bangbang') {
                        script{
                            sh "ls -a"
                            try{
                                sh "chmod +x gradlew"
                                sh "./gradlew clean build"
                            } catch(e){
                                echo "fail build"
                            }
                        }
                    }
                }
            }
        }

        stage('start') {
            steps {
                sh "ls -a"
                sh "docker build -t /backend/bangbang/build/libs/bangbang-0.1.jar"
            }
            steps {
                
            }
        }
    }
}
